[package]
edition = "2021"
name = "guessing_game"
version = "0.1.0"

[dependencies]
rand = "0.8.5"

[profile.release]
debug = false
opt-level = 2
strip = true
#lto = true
#codegen-units = 1   # Reduce number of codegen units to increase optimizations
